name: Build and push Docker images + test for dagster

on:
  pull_request: # Only builds image, does not deploy
    types: [labeled, unlabeled, opened, synchronize, reopened, closed]
    branches:
      - main
    paths-ignore:
      - '**.md'
  push:
    branches: # Build image, push tags latest/stage, deploy to stage
      - main
    tags: # Build image, push tags v0.X/prod, deploy to prod
      - '*'
    paths-ignore:
      - '**.md'

jobs:
  run-dagster-ci:
    # this line shouldn't change, but make sure it's pointed at the main branch
    uses: 20treeAI/github-workflows/.github/workflows/dagster.yml@main
    with:
      # name of the docker image to build
      image_name: my-dagster-docker-image
      # which github branch this is for
      branch: main
      # GCP project you're deploying to
      gcp_project: myproj-1234
      # location you're deploying your project to, defaults to europe-west4
      gcp_location: 'europe-west4'
      # name of the k8s cluster you'd like to deploy to
      cluster_name: my-gke-cluster-name
      # name of the k8s cluster you'd like to deploy to
      stage_cluster_name: my-staging-gke-cluster-name
      # FQDN of the k8s cluster you'd like to deploy to
      stage_cluster_domain: mycooldomain.rocks
      # FQDN of the auth domain for your k8s cluster
      stage_auth_domain: auth.mycooldomain.rocks
      # the service account that will be used by dagster in k8s
      stage_dagster_service_account_name: dagster-service-account
      # optional: Only required if you want a version other than 1.2.2
      dagster_version: '1.2.2'
      # optional: Driver to use for docker buildx. Set to docker from docker-container to help troubleshoot/fix issues
      docker_buildx_driver: 'docker-container'
    # these must be created as github repo secrets
    secrets:
      SSH_KEY: ${{ secrets.BOT_SSH_KEY }}
      GCR_RW_SERVICEACCOUNT_KEY: ${{ secrets.GCR_RW_SERVICEACCOUNT_KEY }}
