---
name: Terraform - Planning, Deployment
# ensures you don't run any additional workflows at the same time as one another to prevent state locking issues
concurreny: terraform_workflow
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'

jobs:
  dev-deploy:
    uses: 20treeAI/github-workflows/.github/workflows/terraform.yml@main
    with:
      terraform_workspace: 'dev'
      github_environment: 'dev'
    secrets:
      SSH_KEY: ${{ secrets.PRIVATE_REPO_SSH_KEY }}
      GCP_TERRAFORM_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_TERRAFORM_SERVICE_ACCOUNT_KEY }}
      TF_GITHUB_APP_ID: ${{ secrets.TF_GITHUB_APP_ID }}
      TF_GITHUB_APP_INSTALLATION_ID: ${{ secrets.TF_GITHUB_APP_INSTALLATION_ID }}
      TF_GITHUB_APP_PEM_FILE: ${{ secrets.TF_GITHUB_APP_PEM_FILE }}

  prod-deploy:
    # only run plan and deploy to prod on pushes to main
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    # this will not run until the previous job's terraform apply is successful
    needs: dev-deploy
    uses: 20treeAI/github-workflows/.github/workflows/terraform.yml@main
    with:
      terraform_workspace: 'prod'
      github_environment: 'prod'
    secrets:
      SSH_KEY: ${{ secrets.PRIVATE_REPO_SSH_KEY }}
      GCP_TERRAFORM_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_TERRAFORM_SERVICE_ACCOUNT_KEY }}
      TF_GITHUB_APP_ID: ${{ secrets.TF_GITHUB_APP_ID }}
      TF_GITHUB_APP_INSTALLATION_ID: ${{ secrets.TF_GITHUB_APP_INSTALLATION_ID }}
      TF_GITHUB_APP_PEM_FILE: ${{ secrets.TF_GITHUB_APP_PEM_FILE }}
