name: Deploy to Cloud Run and Create Sentry Release

on:
  workflow_call:
    inputs:
      image_name:
        description: 'Docker image name'
        required: true
        type: string
      image_tag:
        description: 'Name of tag for docker image'
        required: false
        type: string
      gcp_project:
        description: 'GCP project where GCR is located for storing built Docker images'
        required: true
        type: string
      cloud_run:
        description: 'Whether or not to deploy to Google Cloud Run'
        default: true
        type: boolean
      service_name:
        description: 'Name of service to update in Cloud Run'
        required: true
        type: string
      sentry_release:
        description: 'Whether or not to create a Sentry release for the this project'
        required: false
        default: false 
        type: boolean
      environment:
        description: 'Environment to deploy to: stage or prod'
        required: true
        default: 'stage'
        type: string
    secrets:
      CLOUDRUN_DEPLOYER_SERVICEACCOUNT_KEY:
        description: 'Service Account key for the cloud run deployer'
        required: true
      SENTRY_AUTH_TOKEN:
        description: 'Token for sentry auth'
        required: false

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Cloud SDK
        if: ${{ inputs.image_tag }}
        uses: google-github-actions/setup-gcloud@v1.1.0
        with:
          credentials_json: '${{ secrets.CLOUDRUN_DEPLOYER_SERVICEACCOUNT_KEY }}'

      - name: Tag prod Docker image
        if: ${{ inputs.image_tag }}
        run: gcloud container images add-tag '${{ inputs.image_name }}:${{ github.sha }}' '${{ inputs.image_name }}:${{ inputs.image_tag }}'

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1.0.0
        with:
          service: ${{ inputs.service_name }}
          region: europe-west4
          image: 'eu.gcr.io/${{ inputs.gcp_project }}/${{ inputs.image_name }}:${{ github.sha }}'
          credentials: ${{ secrets.CLOUDRUN_DEPLOYER_SERVICEACCOUNT_KEY }}

      - name: Create Sentry release
        if: ${{ inputs.create_sentry_release }}
        uses: getsentry/action-release@v1.3.1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: ${{ inputs.environment }}
          sourcemaps: './build'
