---
name: docker workflow - build and push docker images to GAR and optionally test with dagster

on:
  workflow_call:
    inputs:
      artifacts_object_name:
        description: 'Name of the artifacts object to pass to docker build job'
        required: false
        type: string
      artifacts_path:
        description: 'Path to use for the artifacts object. Defaults to build/'
        default: 'build/'
        required: false
        type: string
      image_name:
        description: 'Docker image name'
        required: true
        type: string
      branch:
        description: 'Git branch used for tagging incremental builds of the Docker image'
        default: 'main'
        required: false
        type: string
      gcp_project:
        description: 'GCP project where GAR is located for storing built Docker images'
        required: true
        type: string
      test_dagster:
        description: 'whether or not to test dagster compatibility of built docker image'
        required: false
        default: false
        type: boolean
      skip_image_push:
        description: 'whether to skip pushing the docker image'
        required: false
        default: false
        type: boolean
      docker_buildx_driver:
        description: 'Driver to use for docker buildx. Set to docker from docker-container to help troubleshoot/fix issues.'
        required: false
        default: 'docker-container'
        type: string
      clear_space:
        description: 'Whether to clear some space on the runner, e.g. for large (CUDA) builds'
        required: false
        default: false
        type: boolean

    secrets:
      SSH_KEY:
        description: 'SSH key used to access private repos during the build'
        required: true
      GCR_RW_SERVICEACCOUNT_KEY:
        description: 'Service account credentials to push/pull Docker images'
        required: true
      DOCKER_BUILD_SERVICEACCOUNT_KEY:
        description: 'Service account credentials for building Docker images'
        required: false

jobs:
  docker-build-test-push:
    env:
      IMAGE_NAME: europe-west4-docker.pkg.dev/${{ inputs.gcp_project }}/image/${{ inputs.image_name }}
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Clear some space  # https://github.com/apache/flink/blob/master/tools/azure-pipelines/free_disk_space.sh 
        if: ${{ inputs.clear_space }}
        run: |
          df -h
          # sudo apt remove -y '^dotnet-.*'
          # sudo apt remove -y '^llvm-.*'
          # sudo apt remove -y '^mongodb-.*'
          # sudo apt remove -y '^mysql-.*'
          # sudo apt remove -y azure-cli google-chrome-stable firefox powershell mono-devel libgl1-mesa-dri
          # sudo apt autoremove -y
          # sudo apt clean
          # df -h
          # echo "Removing large directories"
          # sudo rm -rf /usr/share/dotnet/
          # sudo rm -rf /usr/local/graalvm/
          # sudo rm -rf /usr/local/.ghcup/
          # sudo rm -rf /usr/local/share/powershell
          # sudo rm -rf /usr/local/share/chromium
          # sudo rm -rf /usr/local/lib/android
          # sudo rm -rf /usr/local/lib/node_modules
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          df -h

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH Keys and known_hosts
        shell: bash -l {0}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a ${{ env.SSH_AUTH_SOCK }}> /dev/null
          ssh-add - <<< "${{ secrets.SSH_KEY }}"

      - name: Import build key
        run: 'echo "${{secrets.DOCKER_BUILD_SERVICEACCOUNT_KEY}}" | base64 -d > /tmp/build_key.json'
        shell: bash -l {0}

      - if: ${{ inputs.artifacts_object_name }}
        name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifacts_object_name }}
          path: ${{ inputs.artifacts_path }}

      - name: Set up docker  # latest docker version to make driver: docker work with gha cache
        uses: crazy-max/ghaction-setup-docker@v3
        with:
          version: latest
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Set up Docker Buildx 
        uses: docker/setup-buildx-action@v3
        with:
          driver: ${{ inputs.docker_buildx_driver }}

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCR_RW_SERVICEACCOUNT_KEY }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Use glcoud CLI to configure-docker auth
        run: gcloud auth configure-docker eu.gcr.io,europe-west4-docker.pkg.dev

      - if: ${{ inputs.test_dagster }}
        name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: ${{ inputs.docker_buildx_driver == 'docker-container' && true || false }}
          push: false
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          ssh: ${{ env.SSH_AUTH_SOCK }},default
          build-args: "GIT_COMMIT=${{ github.sha }}"
          secret-files: BUILD_KEY=/tmp/build_key.json
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - if: ${{ inputs.test_dagster }}
        name: Find repository.py file
        id: find_repo_file
        run: echo "REPOSITORY_PY_LOCATION=$(find . -maxdepth 2 -name repository.py)" >> $GITHUB_OUTPUT

      - if: ${{ inputs.test_dagster }}
        name: Test Dagster Docker image
        run: |
          docker run -p 8080:8080 -d --env 'TZ=Europe/Brussels' --name test_container ${{ env.IMAGE_NAME }}:${{ github.sha }} \
              dagster api grpc -h 0.0.0.0 -p 8080 --python-file "/dagster/${{ steps.find_repo_file.outputs.REPOSITORY_PY_LOCATION }}"
          sleep 5
          wget -O/tmp/grpc_health_probe -q https://github.com/grpc-ecosystem/grpc-health-probe/releases/download/v0.4.11/grpc_health_probe-linux-amd64
          chmod +x /tmp/grpc_health_probe
          for i in $(seq 1 10); do /tmp/grpc_health_probe -addr=localhost:8080 && s=0 && break || s=$? && sleep 2; done; (docker logs test_container && exit $s)

      - name: Push docker image
        # if either a tag isn't provided, or if the run is scheduled (using automatic docker re-builds) for security
        if: ${{ !startsWith(github.ref, 'refs/tags/') || github.event_name == 'scheduled' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ !inputs.skip_image_push }}
          ssh: ${{ env.SSH_AUTH_SOCK }},default
          build-args: "GIT_COMMIT=${{ github.sha }}"
          secret-files: BUILD_KEY=/tmp/build_key.json
          tags: |
            "${{ env.IMAGE_NAME }}:${{ github.sha }}"
            ${{ github.event_name == 'pull_request' && format('{0}:pr-{1}', env.IMAGE_NAME, github.event.number) || '' }}
            ${{ github.ref == format('refs/heads/{0}', inputs.branch) && format('{0}:latest', env.IMAGE_NAME) || '' }}
            ${{ github.ref == format('refs/heads/{0}', inputs.branch) && format('{0}:stage', env.IMAGE_NAME) || '' }}
          provenance: false

      # if either a tag is provided, run re-tag the image with prod and the commit hash
      - if: startsWith(github.ref, 'refs/tags/')
        name: Set release tags
        run: |
          gcloud artifacts docker tags add '${{ env.IMAGE_NAME }}:${{ github.sha }}' '${{ env.IMAGE_NAME }}:${{ github.ref_name }}'
          gcloud artifacts docker tags add '${{ env.IMAGE_NAME }}:${{ github.sha }}' '${{ env.IMAGE_NAME }}:prod'
