name: yarn - build and test

# https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow
on:
  workflow_call:
    secrets:
      REACT_APP_MAPBOX_TOKEN_STAGE:
        description: 'staging mapbox token to be passed to the yarn build'
        required: false
      REACT_APP_MAPBOX_TOKEN_PROD:
        description: 'prod mapbox token to be passed to the yarn build'
        required: false

jobs:
  build:
    name: Build and Test with Yarn
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-v2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v2-

      - name: Install dependencies
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: install # will run `yarn install` command

      - name: Build application
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: build # will run `yarn build` command
        env: 
          REACT_APP_MAPBOX_TOKEN_STAGE: ${{ secrets.REACT_APP_MAPBOX_TOKEN_STAGE }}
          REACT_APP_MAPBOX_TOKEN_PROD: ${{ secrets.REACT_APP_MAPBOX_TOKEN_PROD }}

      - name: Test application
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: test # will run `yarn test` command

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/
          retention-days: 1
